---
method: http
# Match debmirror's defaults for source, components and rsync_extras
source:
  host: paltec.app.diplomatie.gouv.fr
  root: debian
components:
  - main
  - contrib
  - non-free
  - main/debian-installer
rsync_extras:
  - none
# Almost all my systems are x86_64
architectures:
  - amd64