---
method: http
# Match debmirror's defaults for source, components and rsync_extras
source:
  host: ftp.fr.debian.org
  root: debian
components:
  - main
  - contrib
  - non-free
  - main/debian-installer
rsync_extras:
  - none
# Almost all my systems are x86_64
architectures:
  - amd64
# Extra options (include/exclude mostly)
extra_options: "--exclude-deb-section=comm --exclude-deb-section=devel --exclude-deb-section=doc --exclude-deb-section=electronics --exclude-deb-section=embedded --exclude-deb-section=games --exclude-deb-section=gnome --exclude-deb-section=kde --exclude-deb-section=graphics --exclude-deb-section=hamradio --exclude-deb-section=haskell --exclude-deb-section=kde --exclude-deb-section=libdevel --exclude-deb-section=math --exclude-deb-section=misc --exclude-deb-section=net --exclude-deb-section=news --exclude-deb-section=oldlibs --exclude-deb-section=otherosfs --exclude-deb-section=perl --exclude-deb-section=python --exclude-deb-section=science --exclude-deb-section=shells --exclude-deb-section=sound --exclude-deb-section=tex --exclude-deb-section=text --exclude-deb-section=x11 --exclude-deb-section=xorg --exclude-deb-section=zope --exclude='/Translation-.*\.bz2$' --include='(/Translation-en.bz2)' --include='(/Translation-fr.bz2)' --include='(/Translation-en)' --include='(/Translation-fr)' --include='/Translation-fr.*\.bz2$' --exclude='(kfreebsd-.*)' --exclude='(/.*r-bioc.*)' --exclude='(/.*dbgsym.*)' --exclude='(/.*dbg_.*)'"