# apt: apache2
- name: Ensure Apache is installed on Debian.
  become: true
  apt: 
    name: apache2 
    state: present
    update_cache: yes 
    cache_valid_time: 3600

- name: Disable mpm_event/mpm_worker, enable mpm_prefork and required module
  become: true
  community.general.apache2_module:
    name: "{{ item.module }}"
    state: "{{ item.state }}"
    warn_mpm_absent: false
    ignore_configcheck: true
  loop:
  - module: mpm_worker
    state: absent
  - module: mpm_event
    state: absent
  - module: mpm_prefork
    state: present
  - module: rewrite
    state: present
  - module: autoindex
    state: present

- name: Creating file /var/repos/mirrorvhost.conf
  become: true
  copy:
    dest: /etc/apache2/sites-available/mirrorvhost.conf
    src: mirrorvhost.conf

- name: Disable default vhost
  become: true
  command: /usr/sbin/a2dissite 000-default
- name: Enable mirror vhost
  become: true
  command: /usr/sbin/a2ensite mirrorvhost
- name: Creating file favicon.ico,HEADER.html,README.html
  become: true
  copy:
    dest: "/var/repos/{{item}}"
    src: "{{item}}"
    owner: root
    group: mirror
    mode: 0664
  loop:
  - favicon.ico
  - HEADER.html
  - README.html

- name: Restart service apache2
  become: true
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Clone git
  ansible.builtin.git:
    repo: 'http://mirror.lab.loxda.net/git/autoindex_strapdown.git/'
    dest: /var/repos/autoindex

- name: Generate .htaccess
  become: true
  shell: |
    rm /var/repos/.htaccess; 
    for dir in $(ls -1 /var/repos --ignore=gems --ignore=git --ignore=keyrings --ignore=lost+found --ignore=old --ignore=autoindex --ignore=*.html); do 
    echo "AddDescription \"$(grep "Upstream-Mirror:" /var/repos/$dir/project/trace/mirror.lab.loxda.net) $(grep "Date:" /var/repos/$dir/project/trace/mirror.lab.loxda.net)\" $dir" >> /var/repos/.htaccess; 
    done
    echo "AddDescription \"mirror from https://rubygems.org\" gems" >> /var/repos/.htaccess
    echo "AddDescription \"mirror from various git repositories\" git" >> /var/repos/.htaccess
  tags: frontend