---

- hosts: localhost
  gather_facts: false
  # become: true

  vars:
    mirror_base_path: /var/repos
    # proxy: http://127.0.0.1:3128/
    # my_git_deploy_credentials: 'user:password'

  pre_tasks:

    - name: Stat mirrors directory
      ansible.builtin.stat:
        path: '{{ mirror_base_path }}'
      register: mirror_path_stat

    - name: Fail if mirrors directory does not exist
      ansible.builtin.fail:
        msg: 'Please pre-create the mirror target directory (currently set as {{ mirror_base_path }}'
      when: not mirror_path_stat.stat.exists

    - name: Make sure keyrings directory exists
      ansible.builtin.file:
        path: '{{ mirror_base_path }}/keyrings'
        state: directory

  roles:
    # - { role: centos-mirrors, tags: ['centos','never'] }
    # - { role: rocky-mirrors, tags: ['rocky','never'] }
    - { role: debian-mirrors, tags: ['debian'] }
    - { role: proxmox-mirrors, tags: ['proxmox'] }
    - { role: hwraid-mirrors, tags: ['hwraid'] }
    - { role: hpelinux-mirrors, tags: ['hpelinux'] }
    - { role: foreman-mirrors, tags: ['foreman'] }
    - { role: puppetlabs-mirrors, tags: ['puppetlabs','never'] }
    # - { role: git-mirrors, tags: ['git','never'] }

  # tasks:
  # apt: apache2
  # apache2: vhost:80 /var/repos
  # apache2: mod_autoindex
  # file: /var/repos/HEADER.html
  # file: /var/repos/README.html
  # service: restart apache2
