---

- hosts: localhost
  gather_facts: false

  vars:
    mirror_base_path: /var/repos
    # proxy: http://127.0.0.1:3128/
    # my_git_deploy_credentials: 'user:password'

  pre_tasks:

    - name: Stat mirrors directory
      ansible.builtin.stat:
        path: '{{ mirror_base_path }}'
      register: mirror_path_stat

    - name: Fail if mirrors directory does not exist
      ansible.builtin.fail:
        msg: 'Please check or create the mirror target directory (currently set as {{ mirror_base_path }}'
      when: not mirror_path_stat.stat.exists

    - name: Make sure keyrings directory exists
      ansible.builtin.file:
        path: '{{ mirror_base_path }}/keyrings'
        state: directory

  roles:
    # - { role: centos-mirrors, tags: ['centos','never'] }
    # - { role: rocky-mirrors, tags: ['rocky','never'] }
    - { role: debian-mirrors, tags: ['debian'] }
    - { role: proxmox-mirrors, tags: ['proxmox'] }
    - { role: hwraid-mirrors, tags: ['hwraid'] }
    - { role: hpelinux-mirrors, tags: ['hpelinux'] }
    - { role: foreman-mirrors, tags: ['foreman'] }
    - { role: puppetlabs-mirrors, tags: ['puppetlabs','never'] }
    - { role: git-mirrors, tags: ['git','never'] }

  # tasks:
  #   # apt: apache2
  #   - name: Ensure Apache is installed on Debian.
  #     apt: 
  #       name: apache2 
  #       state: present
  #       update_cache: yes 
  #       cache_valid_time: 3600
  #   - name: Disable mpm_event/mpm_worker, enable mpm_prefork and ignore warnings about missing mpm module
  #     community.general.apache2_module:
  #       name: "{{ item.module }}"
  #       state: "{{ item.state }}"
  #       warn_mpm_absent: false
  #       ignore_configcheck: true
  #     loop:
  #     - module: mpm_worker
  #       state: absent
  #     - module: mpm_event
  #       state: absent
  #     - module: mpm_prefork
  #       state: present
  #   # apache2: vhost:80 /var/repos
  #   # apache2: mod_autoindex
  #   - name: Enable mod_autoindex
  #     community.general.apache2_module:
  #       state: present
  #       name: autoindex
  #       force: true
  #   # file: /var/repos/HEADER.html
  #   - name: Creating file /var/repos/HEADER.html
  #     copy:
  #       dest: /var/repos/HEADER.html
  #       file: HEADER.html
  #       owner: root
  #       group: mirror
  #       mode: 0664
  #   # file: /var/repos/README.html
  #   - name: Creating file /var/repos/README.html
  #     copy:
  #       dest: /var/repos/README.html
  #       file: README.html
  #       owner: root
  #       group: mirror
  #       mode: 0664
  #   - name: Restart service apache2
  #     ansible.builtin.service:
  #       name: apache2
  #       state: restarted
