---

- hosts: localhost
  gather_facts: false

  vars:
    mirror_base_path: /var/repos
    # proxy: http://127.0.0.1:3128/

  pre_tasks:

    - name: Make sure mirror directory exists
      ansible.builtin.file:
        path: '{{ mirror_base_path }}'
        state: directory

    - name: Make sure keyrings directory exists
      ansible.builtin.file:
        path: '{{ mirror_base_path }}/keyrings'
        state: directory

  roles:
    # - { role: centos-mirrors, tags: ['centos','never'] }
    # - { role: rocky-mirrors, tags: ['rocky','never'] }
    - { role: debian-mirrors, tags: ['debian'] }
    - { role: proxmox-mirrors, tags: ['proxmox'] }
    - { role: hwraid-mirrors, tags: ['hwraid'] }
    - { role: hpelinux-mirrors, tags: ['hpelinux'] }
    - { role: foreman-mirrors, tags: ['foreman'] }
    - { role: puppetlabs-mirrors, tags: ['puppetlabs'] }
    - { role: git-mirrors, tags: ['git'] }

  tasks:

    - name: Include web frontend prepare
      ansible.builtin.include_tasks:
        file: frontend.yml
