---

- hosts: localhost
  gather_facts: false

  vars:
    mirror_base_path: /var/repos
    # proxy: http://172.16.202.253:3128/

  pre_tasks:

    - name: Make sure mirror directory exists
      ansible.builtin.file:
        path: "{{ mirror_base_path }}"
        state: directory

    - name: Make sure keyrings directory exists
      ansible.builtin.file:
        path: "{{ mirror_base_path }}/keyrings"
        state: directory

  roles:
    # - { role: centos-mirrors, tags: ['centos','never'] }
    # - { role: rocky-mirrors, tags: ['rocky','never'] }
    - { role: debian-mirrors, tags: ['debian'] }
    - { role: proxmox-mirrors, tags: ['proxmox'] }
    - { role: hwraid-mirrors, tags: ['hwraid'] }
    - { role: hpelinux-mirrors, tags: ['hpelinux'] }
    - { role: foreman-mirrors, tags: ['foreman'] }
    - { role: puppetlabs-mirrors, tags: ['puppetlabs'] }
    - { role: git-mirrors, tags: ['git'] }

  tasks:

    - name: Download syslinux-3.86.tar.gz archive from kernel.org
      get_url:
        url: https://mirrors.edge.kernel.org/pub/linux/utils/boot/syslinux/3.xx/syslinux-3.86.tar.gz
        dest: "{{ mirror_base_path }}/syslinux-3.86.tar.gz"

    - name: Download foreman_discovery_image archive from theforeman.org
      get_url:
        url: http://downloads.theforeman.org/discovery/releases/latest/fdi-image-latest.tar
        dest: "{{ mirror_base_path }}/fdi-image-latest.tar"

    - name: Include web frontend prepare
      ansible.builtin.include_tasks:
        file: frontend.yml
