---

- name: Make target directory
  ansible.builtin.file:
    path: "{{ target }}"
    state: directory

- name: Make keys directory
  ansible.builtin.file:
    path: "{{ keyring_directory }}/keys.d"
    state: directory
  when: keys is defined

- name: Download key {{ key.name }}
  ansible.builtin.get_url:
    dest: "{{ keyring_directory }}/keys.d/{{ key.name }}.key"
    url: "{{ key.url }}"
    checksum: "{{ key.checksum| default('') }}"
  loop: "{{ keys | default([]) }}"
  loop_control:
    loop_var: key

- name: Delete any extra keys
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob: "{{ keyring_directory }}/keys.d/*.key"
  when: item.split('/')[-1].split('.')[0] not in keys | map(attribute='name') | list

- name: Delete old keyring
  ansible.builtin.file:
    path: "{{ keyring_directory }}/keyring.gpg"
    state: absent

- name: Make keyring
  ansible.builtin.shell: gpg --no-default-keyring --keyring {{ keyring_directory }}/keyring.gpg --import {{ item }}
  with_fileglob: "{{ keyring_directory }}/keys.d/*.key"

# command that uses non-posix shell-isms (in this example /bin/sh doesn't handle redirection and wildcards together but bash does)
- name: Run debmirror
  vars:
    argv_start:
      - /usr/bin/debmirror
      - --method={{ method }}
      - --dist={{ ','.join(suites) }}
      - --section={{ ','.join(components) }}
      - --arch={{ ','.join(architectures) }}
      - --rsync-extra={{ ','.join(rsync_extras) }}
      - --host={{ source.host }}
      - --root={{ source.root }}
      - --keyring={{ keyring_directory }}/keyring.gpg
    argv_end:
      - "{{ target }}"
  ansible.builtin.shell: |
    {{ argv_start | join(' ') }} \
    {% if proxy %}--proxy={{ proxy }} \{% else "" endif %}
    {{ extra_options | join(' ') }} \
    {{ argv_end  | join(' ') }}
  args:
    executable: /bin/bash

#      - --slow-cpu # self explanatory
#      - --precleanup # Remove old files before download - makes mirror inconsistent until debmirror finishes but copes better with limited space
#      - --postcleanup # Remove old files after download - makes mirror consistent while debmirror runs but consume more space
