---
dependencies:

  - role: debmirror
    method: http
    rsync_extras: ['none']
    source:
      host: download.proxmox.com
      root: //debian/pve
    target: '{{ mirror_base_path }}/proxmox'
    keyring_directory: '{{ mirror_base_path }}/keyrings/proxmox'
    suites:
      - bullseye
    components:
      - pve-no-subscription
    keys:
      - name: proxmox-keyring
        url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    extra_options:
      - --dryrun
      - --verbose
      - --nosource
      - --cleanup
      - --exclude='(/.*dbgsym.*)'
      - --exclude='(/.*dbg_.*)'
      - --exclude='(/.*debug_.*)'
      - --exclude='(/pve-kernel-5.10\..*)'
      - --exclude='(/pve-headers-5.10\..*)'
      - --exclude='(/pve-kernel-5.11\..*)'
      - --exclude='(/pve-headers-5.11\..*)'
      - --exclude='(/pve-kernel-5.13\..*)'
      - --exclude='(/pve-headers-5.13\..*)'
      - --exclude='(/pve-kernel-5.15\..*)'
      - --exclude='(/pve-headers-5.15\..*)'
      - --exclude='(/pve-kernel-5.\..*)'
      - --exclude='(/pve-headers-5.\..*)'
      - --exclude='(/pve-firmware_3.5-6_.*)'
      - --exclude='(/pve-firmware_3.6-1_.*)'
      - --exclude='(/pve-firmware_3.6-2_.*)'
      - --exclude='(/pve-firmware_3.6-3_.*)'
      - --exclude='(/pve-firmware_3.6-4_.*)'

  - role: debmirror
    method: http
    rsync_extras: ['none']
    source:
      host: download.proxmox.com
      root: //debian/pbs
    target: '{{ mirror_base_path }}/proxmox-pbs'
    keyring_directory: '{{ mirror_base_path }}/keyrings/proxmox-pbs'
    suites:
      - bullseye
    components:
      - pbs-no-subscription
    keys:
      - name: proxmox-keyring
        url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
    extra_options:
      - --dryrun
      - --verbose
      - --nosource
      - --cleanup
      - --exclude='(/.*dbgsym.*)'
      - --exclude='(/.*dbg_.*)'
      - --exclude='(/.*debug_.*)'
      - --exclude='(/pve-kernel-5.10\..*)'
      - --exclude='(/pve-headers-5.10\..*)'
      - --exclude='(/pve-kernel-5.11\..*)'
      - --exclude='(/pve-headers-5.11\..*)'
      - --exclude='(/pve-kernel-5.13\..*)'
      - --exclude='(/pve-headers-5.13\..*)'
      - --exclude='(/pve-kernel-5.15\..*)'
      - --exclude='(/pve-headers-5.15\..*)'
      - --exclude='(/pve-kernel-5.\..*)'
      - --exclude='(/pve-headers-5.\..*)'
      - --exclude='(/pve-kernel-6\.1.*)'

  # - role: debmirror
  #   method: http
  #   rsync_extras: ['none']
  #   source:
  #     host: download.proxmox.com
  #     root: debian/ceph-pacific
  #   target: '{{ mirror_base_path }}/ceph-pacific'
  #   keyring_directory: '{{ mirror_base_path }}/keyrings/ceph-pacific'
  #   suites:
  #     - bullseye
  #   components:
  #     - main
  #   keys:
  #     - name: proxmox-keyring
  #       url: https://enterprise.proxmox.com/debian/proxmox-release-bullseye.gpg
  #       checksum: 'sha512:7fb03ec8a1675723d2853b84aa4fdb49a46a3bb72b9951361488bfd19b29aab0a789a4f8c7406e71a69aabbc727c936d3549731c4659ffa1a08f44db8fdcebfa'