---
dependencies:
  - role: git-bare
    repository: https://github.com/mythic-beasts/dehydrated-mythic-dns01.git
    target: '{{ mirror_base_path }}/git/github.com/mythic-beasts/dehydrated-mythic-dns01.git/'
  - role: git-bare
    repository: https://github.com/loz-hurst/dehydrated-code-rack.git
    target: '{{ mirror_base_path }}/git/github.com/loz-hurst/dehydrated-code-rack.git/'
  - role: git-bare
    repository: https://github.com/loz-hurst/cron-wrapper.git
    target: '{{ mirror_base_path }}/git/github.com/loz-hurst/cron-wrapper.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@git.my.domain.tld/path/to/salt-home.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/salt-home.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/debian-installer-preseed.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/debian-installer-preseed.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/icinga2-zones-config.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/icinga2-zones-config.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/blog.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/blog.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/mailadm.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/mailadm.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/py-budget.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/py-budget.git/'
  - name: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/py-entek.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/py-entek.git/'
  - name: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/hack-dilbert.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/hack-dilbert.git/'
  - role: git-bare
    repository: https://{{ my_git_deploy_credentials }}@my.domain.tld/path/to/puppet.git
    target: '{{ mirror_base_path }}/git/my.domain.tld/path/to/puppet.git/'