---
dependencies:

  - role: debmirror
    method: http
    rsync_extras: ['none']
    source:
      host: apt.puppetlabs.com
      root: /
    target: '{{ mirror_base_path }}/puppetlabs'
    keyring_directory: '{{ mirror_base_path }}/keyrings/puppetlabs'
    suites:
      - bullseye
    components:
      - puppet7
    keys:
      - name: puppetlabs-keyring
        url: https://apt.puppetlabs.com/keyring.gpg
    extra_options:
      - --nosource
      - --no-check-gpg
      - --diff=none
      - --i18n 
      - --exclude='(/.*-dbg-.*)'
      - --exclude='(/.*-dbg_.*)'
      - --exclude='(/.*-dbgsym_.*)'
